[package]
name = "bakfile"
authors = ["ChanceNCounter <ChanceNCounter@icloud.com>"]
repository = "https://github.com/bakfile/bak"
version = "0.1.0" # tracks version of `bakfile` library, not `bak` binary
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
clap = { version = "4.5.23", features = ["cargo"] }
chrono = "0.4.39"
directories = "5.0.1"
log = "0.4.22"
rusqlite = "0.31.0"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.215", features = ["derive"] }
shellexpand = "3.1.0"
thiserror = "1.0.69"
toml_edit = "0.22.22"
anyhow = "1.0.94"
