use log::trace;
use std::fmt;
use std::path::{Path, PathBuf};
use std::rc::Rc;

use directories::BaseDirs;
use serde::Deserialize;

use crate::util::SystemError;

/* Define defaults */
#[cfg(target_family = "unix")]
static DEFAULT_OPEN_CMD: &str = 
    if cfg!(target_os = "macos") {"open"}
    else {"vim"};
#[cfg(target_family = "unix")]
static DEFAULT_DIFF_CMD: &str = "diff";

#[cfg(target_os = "windows")]
static DEFAULT_OPEN_CMD: &str = "start";
#[cfg(target_os = "windows")]
static DEFAULT_DIFF_CMD: &str = "fd";


pub fn get_config() -> Rc<Config> {
    let config_path = Config::get_config_path().unwrap(); // Look for config file
    let out = match config_path.exists() {
        false => {
            // Config file not found
            let configuration: Config = Config::load(None); // Generate default config file,
            configuration.save().unwrap(); // and write
            Rc::new(configuration)
        }
        true => Rc::new(Config::load(Some(config_path.as_path()))),
    };
    trace!("Generated config object: {:p}", out);
    out
}

pub fn get_default_bakfile_loc() -> Result<PathBuf, SystemError> {
    match BaseDirs::new() {
        Some(base_dirs) => return Ok(base_dirs.data_local_dir().join("bak/bakfiles")),
        None => return Err(SystemError::BASE_DIRS_ERROR),
    }
}

pub fn get_default_bak_db_loc() -> Result<PathBuf, SystemError> {
    match BaseDirs::new() {
        Some(base_dirs) => return Ok(base_dirs.data_local_dir().join("bak/bak.db")),
        None => return Err(SystemError::BASE_DIRS_ERROR.into()),
    }
}

#[derive(Deserialize)]
pub struct Config {
    pub(crate) bakfile_location: String,
    pub(crate) bak_database_location: String,
    pub(crate) bak_open_exec: String,
    pub(crate) bak_diff_exec: String,
    pub(crate) bak_list_relative_paths: bool,
    pub(crate) bak_list_colors: bool,
    pub(crate) bakfile_library_version: semver::Version,
}

impl fmt::Display for Config {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "
            bakfile location: {:?}
            bakfile database: {:?}
            'bak open' command: {:?}
            'bak diff' command: {:?}
            display relative paths (false by default): {:?}
            colorize bak list: {:?}
            
            Config file generated by bak version {:?}
            located at {:?}",
            self.bakfile_location,
            self.bak_database_location,
            self.bak_open_exec,
            self.bak_diff_exec,
            self.bak_list_relative_paths,
            self.bak_list_colors,
            self.bakfile_library_version.to_string(),
            Config::get_config_path().unwrap() // if this doesn't return a path, how did we get here?
        )
    }
}

impl Config {
    fn gen_default() -> Result<Config, SystemError> {
        let basedirs = match BaseDirs::new() {
            Some(basedirs) => basedirs,
            None => {
                return Err(SystemError::BASE_DIRS_ERROR.into());
            }
        };
        Ok(Config {
            bakfile_location: basedirs.data_local_dir().join("bak/bakfiles").to_str().unwrap().to_string(), // this can't be None if we didn't already error out above
            bak_database_location: basedirs.data_local_dir().join("bak/bak.db").to_str().unwrap().to_string(),
            bak_open_exec: DEFAULT_OPEN_CMD.to_string() + " %f",
            bak_diff_exec: DEFAULT_DIFF_CMD.to_string() + " %old %new",
            bak_list_relative_paths: false,
            bak_list_colors: true,
            bakfile_library_version: crate::util::LIBBAKFILE_VERSION(),
        })
    }

    pub fn load(path: Option<&Path>) -> Config {
        let config_path = &Self::get_config_path().unwrap();
        let path = match path {
            Some(path) => path,
            None => &config_path,
        };
        match path.exists() {
            true => (),
            false => {
                // Config file does not exist. Write one.
                let empty_config = Self::gen_default().unwrap();
                empty_config.save().unwrap();
            }
        }
        let i_file = match std::fs::read_to_string(path) {
            Ok(file) => file,
            Err(e) => {
                panic!("Attempted to read invalid config file. {:?}", e);
            }
        };
        let out: Config = match i_file.parse::<toml_edit::DocumentMut>() {
            // TODO internal error handling for this parse run
            Ok(conf) => Config {
                bakfile_location: conf["bakfile_location"].as_str().unwrap().to_string(),
                bak_database_location: conf["bak_database_location"].as_str().unwrap().to_string(),
                bak_open_exec: conf["bak_open_exec"].as_str().unwrap().to_string(),
                bak_diff_exec: conf["bak_diff_exec"].as_str().unwrap().to_string(),
                bak_list_relative_paths: conf["bak_list_relative_paths"].as_bool().unwrap(),
                bak_list_colors: conf["bak_list_colors"].as_bool().unwrap(),
                bakfile_library_version: semver::Version::parse(conf["bak_config_generated_by_library_version"].as_str().unwrap()).unwrap()
            },
            Err(e) => {
                panic!("Config file did not parse to valid TOML. {:?}", e);
            }
        };
        trace!(
            "Generated config object with values:\n
                bakfile location: {}\n
                database location: {}\n
                `bak open` executable: {}\n
                `bak diff` executable: {}\n
                colorize `bak list`: {}\n
                config file generated by version: {}\n",
            out.bakfile_location,
            out.bak_database_location,
            out.bak_open_exec,
            out.bak_diff_exec,
            out.bak_list_colors,
            out.bakfile_library_version
        );
        out
    }

    pub fn save(&self) -> Result<(), std::io::Error> {
        let config_path = Self::get_config_path().unwrap();
        let out_str = crate::config_template::get_config_template_string(&self); // TODO
        match std::fs::write(config_path, out_str.unwrap()) {
            Ok(_) => Ok(()),
            Err(e) => Err(e.into()),
        }
    }

    pub fn get_config_path() -> Result<PathBuf, SystemError> {
        let basedirs = match BaseDirs::new() {
            Some(basedirs) => basedirs,
            None => {
                return Err(SystemError::BASE_DIRS_ERROR.into());
            }
        };
        let config_path = basedirs.config_dir().join(Path::new("bak.conf"));
        Ok(config_path)
    }
}
