use log::trace;
use std::fmt;
use std::path::{Path, PathBuf};
use std::rc::Rc;

use directories::BaseDirs;
use serde::Deserialize;

//use crate::configuration::get_config_template_string as template_string;
use crate::util::SystemError;

pub fn get_config() -> Rc<Config> {
    let config_path = Config::get_config_path().unwrap(); // Look for config file
    let out = match config_path.exists() {
        false => {
            // Config file not found
            let configuration: Config = Config::from_toml(None); // Generate default config file,
            configuration.save().unwrap(); // and write
            Rc::new(configuration)
        }
        true => Rc::new(Config::from_toml(Some(config_path.as_path()))),
    };
    trace!("Generated config object: {:p}", out);
    out
}

pub fn get_default_bakfile_loc() -> Result<PathBuf, SystemError> {
    match BaseDirs::new() {
        Some(base_dirs) => return Ok(base_dirs.data_local_dir().join("bak/bakfiles")),
        None => return Err(SystemError::BASE_DIRS_ERROR),
    }
}

pub fn get_default_bak_db_loc() -> Result<PathBuf, SystemError> {
    match BaseDirs::new() {
        Some(base_dirs) => return Ok(base_dirs.data_local_dir().join("bak/bak.db")),
        None => return Err(SystemError::BASE_DIRS_ERROR.into()),
    }
}

#[derive(Deserialize)]
pub struct Config {
    pub(crate) bakfile_location: String,
    pub(crate) bak_database_location: String,
    pub(crate) bak_open_exec: String,
    pub(crate) bak_diff_exec: String,
    pub(crate) bak_list_relative_paths: bool,
    pub(crate) bak_list_colors: bool,
    pub(crate) bakfile_config_generated_by_library_version: semver::Version,
}

impl fmt::Display for Config {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "
            bakfile location: {:?}
            bakfile database: {:?}
            'bak open' command: {:?}
            'bak diff' command: {:?}
            display relative paths (false by default): {:?}
            colorize bak list: {:?}
            
            Config file generated by bak version {:?}
            located at {:?}",
            self.bakfile_location,
            self.bak_database_location,
            self.bak_open_exec,
            self.bak_diff_exec,
            self.bak_list_relative_paths,
            self.bak_list_colors,
            self.bakfile_config_generated_by_library_version.to_string(),
            Config::get_config_path().unwrap() // if this doesn't return a path, how did we get here?
        )
    }
}

impl Config {
    fn gen_empty() -> Config {
        Config {
            bakfile_location: "default".to_string(),
            bak_database_location: "default".to_string(),
            bak_open_exec: "default".to_string(),
            bak_diff_exec: "default".to_string(),
            bak_list_relative_paths: false,
            bak_list_colors: true,
            bakfile_config_generated_by_library_version: crate::util::LIBBAKFILE_VERSION(),
        }
    }

    pub fn from_toml(path: Option<&Path>) -> Config {
        let config_path = &Self::get_config_path().unwrap();
        let path = match path {
            Some(path) => path,
            None => &config_path,
        };
        match path.exists() {
            true => (),
            false => {
                // Config file does not exist. Write one.
                let empty_config = Self::gen_empty();
                empty_config.save().unwrap();
            }
        }
        let i_file = match std::fs::read_to_string(path) {
            Ok(file) => file,
            Err(e) => {
                panic!("Attempted to read invalid config file. {:?}", e);
            }
        };
        let out: Config = match toml::from_str(i_file.as_str()) {
            Ok(conf) => conf,
            Err(e) => {
                panic!("Config file did not parse to valid TOML. {:?}", e);
            }
        };
        trace!(
            "Generated config object with values:\n
                bakfile location: {}\n
                database location: {}\n
                `bak open` executable: {}\n
                `bak diff` executable: {}\n
                colorize `bak list`: {}\n
                config file generated by version: {}\n",
            out.bakfile_location,
            out.bak_database_location,
            out.bak_open_exec,
            out.bak_diff_exec,
            out.bak_list_colors,
            out.bakfile_config_generated_by_library_version
        );
        out
    }

    pub fn save(&self) -> Result<(), std::io::Error> {
        let config_path = Self::get_config_path().unwrap();
        // let out_str = template_string(&self)?;
        let out_str = "TODO"; // TODO
        match std::fs::write(config_path, out_str) {
            Ok(_) => Ok(()),
            Err(e) => Err(e.into()),
        }
    }

    pub fn get_config_path() -> Result<PathBuf, SystemError> {
        let basedirs = match BaseDirs::new() {
            Some(basedirs) => basedirs,
            None => {
                return Err(SystemError::BASE_DIRS_ERROR.into());
            }
        };
        let config_path = basedirs.config_dir().join(Path::new("bak.conf.toml"));
        Ok(config_path)
    }
}
