use log::trace;
use std::fmt;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::rc::Rc;

use directories::BaseDirs;

use crate::config_template::get_config_template_string;
use crate::util::SystemError;

/* Define defaults */
#[cfg(target_family = "unix")]
pub(crate) static DEFAULT_OPEN_CMD: &str = 
    if cfg!(target_os = "macos") {"open"}
    else {"vim"};
#[cfg(target_family = "unix")]
pub(crate) static DEFAULT_DIFF_CMD: &str = "diff";
#[cfg(target_family = "unix")]
pub(crate) static DEFAULT_CP_CMD: &str = "cp";

#[cfg(target_os = "windows")]
pub(crate) static DEFAULT_OPEN_CMD: &str = "start";
#[cfg(target_os = "windows")]
pub(crate) static DEFAULT_DIFF_CMD: &str = "fd";
#[cfg(target_os = "windows")]
pub(crate) static DEFAULT_CP_CMD: &str = "copy";

pub fn get_config() -> Rc<Config> {
    let config_path = Config::get_config_path().unwrap(); // Look for config file
    let out = match config_path.exists() {
        false => {
            // Config file not found
            let configuration: Config = Config::load(None); // Generate default config file,
            configuration.save(None).unwrap(); // and write
            Rc::new(configuration)
        }
        true => Rc::new(Config::load(Some(config_path.as_path()))),
    };
    trace!("loaded config: {}", out);
    out
}

pub(crate) fn get_default_bakfile_loc() -> Result<PathBuf, SystemError> {
    match BaseDirs::new() {
        Some(base_dirs) => return Ok(base_dirs.data_local_dir().join("bak/bakfiles")),
        None => return Err(SystemError::BASE_DIRS_ERROR),
    }
}

pub(crate) fn get_default_bak_db_loc() -> Result<PathBuf, SystemError> {
    match BaseDirs::new() {
        Some(base_dirs) => return Ok(base_dirs.data_local_dir().join("bak/bak.db")),
        None => return Err(SystemError::BASE_DIRS_ERROR),
    }
}

pub struct Config {
    pub bakfile_location: String,
    pub bak_database_location: String,
    pub bak_cp_exec: Option<String>,
    pub bak_open_exec: String,
    pub bak_diff_exec: String,
    pub bak_list_relative_paths: bool,
    pub bak_list_colors: bool,
    pub bak_list_diff: bool,
    pub quiet: bool,
    pub bakfile_library_version: semver::Version,
    toml: Option<toml_edit::DocumentMut>
}

impl fmt::Display for Config {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "
            bakfile location: {:?}
            bakfile database: {:?}
            file copy command (built-in function if None): {:?}
            'bak open' command: {:?}
            'bak diff' command: {:?}
            display relative paths (false by default): {:?}
            colorize bak list: {:?}
            suppress confirmation prompts: {:?}
            bak list notes changed files: {:?}
            config file generated by bak version {:?}
            located at {:?}",
            self.bakfile_location,
            self.bak_database_location,
            self.bak_cp_exec.clone().unwrap_or("None".into()),
            self.bak_open_exec,
            self.bak_diff_exec,
            self.bak_list_relative_paths,
            self.bak_list_colors,
            self.bak_list_diff,
            self.quiet,
            self.bakfile_library_version.to_string(),
            Config::get_config_path().unwrap() // if this doesn't return a path, how did we get here?
        )
    }
}

impl Config {
    fn gen_default() -> Result<Config, SystemError> {
        Ok(Config {
            bakfile_location: get_default_bakfile_loc().unwrap().to_str().unwrap().to_string(), // this can't be None if we didn't already error out above
            bak_database_location: get_default_bak_db_loc().unwrap().to_str().unwrap().to_string(),
            bak_cp_exec: Some(DEFAULT_CP_CMD.to_string() + " %old %new"),
            bak_open_exec: DEFAULT_OPEN_CMD.to_string() + " %f",
            bak_diff_exec: DEFAULT_DIFF_CMD.to_string() + " %old %new",
            bak_list_relative_paths: false,
            bak_list_colors: true,
            bak_list_diff: false,
            quiet: false,
            bakfile_library_version: crate::util::LIBBAKFILE_VERSION(),
            toml: None
        })
    }

    pub fn load(path: Option<&Path>) -> Config {
        let config_path = &Self::get_config_path().unwrap();
        let path = match path {
            Some(path) => path,
            None => &config_path,
        };
        match path.exists() {
            true => (),
            false => {
                // Config file does not exist. Write one.
                let empty_config = Self::gen_default().unwrap();
                empty_config.save(Some(path)).unwrap();
            }
        }
        let i_file = match std::fs::read_to_string(path) {
            Ok(file) => file,
            Err(e) => {
                panic!("Attempted to read invalid config file. {:?}", e);
            }
        };
        let out: Config = match i_file.parse::<toml_edit::DocumentMut>() {
            // TODO internal error handling for this parse run
            Ok(conf) => Config {
                bakfile_location: conf["bakfile_location"].as_str().unwrap().to_string(),
                bak_database_location: conf["bak_database_location"].as_str().unwrap().to_string(),
                bak_cp_exec: match conf.get("bak_cp_exec") {
                    Some(val) => Some(val.as_str().unwrap().to_string()),
                    None => None
                },
                bak_open_exec: conf["bak_open_exec"].as_str().unwrap().to_string(),
                bak_diff_exec: conf["bak_diff_exec"].as_str().unwrap().to_string(),
                bak_list_relative_paths: conf["bak_list_relative_paths"].as_bool().unwrap(),
                bak_list_colors: conf["bak_list_colors"].as_bool().unwrap(),
                bak_list_diff: conf["bak_list_diff"].as_bool().unwrap(),
                quiet: conf["quiet"].as_bool().unwrap(),
                bakfile_library_version: semver::Version::parse(conf["bak_config_generated_by_library_version"].as_str().unwrap()).unwrap(),
                toml: Some(conf)
            },
            Err(e) => {
                panic!("Config file did not parse to valid TOML. {:?}", e);
            }
        };
        let cp = match out.bak_cp_exec.as_ref() {
            Some(val) => val,
            None => "None"
        };
        trace!(
            "generated config object with values:
                bakfile location: {}
                database location: {}
                copy executable: {}
                `bak open` executable: {}
                `bak diff` executable: {}
                colorize `bak list`: {}
                `bak list` shows diff status: {}
                suppress prompts: {}
                config file generated by bakfile version: {}",
            out.bakfile_location,
            out.bak_database_location,
            cp,
            out.bak_open_exec,
            out.bak_diff_exec,
            out.bak_list_colors,
            out.bak_list_diff,
            out.quiet,
            out.bakfile_library_version
        );
        out
    }

    pub fn update_toml(&mut self) {
        use toml_edit::Item;
        if self.toml.is_none() {
            self.toml = Some(get_config_template_string(self).unwrap().parse::<toml_edit::DocumentMut>().unwrap());
        }
        
        let mut toml = self.toml.clone().unwrap();
        toml["bakfile_location"] = Item::from(self.bakfile_location.clone());
        toml["bak_database_location"] = Item::from(self.bak_database_location.clone());
        if self.bak_cp_exec.is_some() {
            toml["bak_cp_exec"] = Item::from(self.bak_cp_exec.as_ref().unwrap());
        }
        toml["bak_open_exec"] = Item::from(self.bak_open_exec.clone());
        toml["bak_diff_exec"] = Item::from(self.bak_diff_exec.clone());
        toml["bak_list_relative_paths"] = Item::from(self.bak_list_relative_paths);
        toml["bak_list_colors"] = Item::from(self.bak_list_colors);
        toml["bak_list_diff"] = Item::from(self.bak_list_diff);
        toml["quiet"] = Item::from(self.quiet);
        toml["bak_config_generated_by_library_version"] = Item::from(self.bakfile_library_version.to_string());
        
        self.toml = Some(toml);
    }

    pub fn save(&self, path: Option<&Path>) -> Result<(), anyhow::Error> {
        /*  attached toml has not necessarily been updated since load, as it would be a waste of several chunky operations
            in the overwhelming majority of invocations. it is the responsibility of the command or utility
            updating this config struct to subsequently call its update_toml() function */
        let config_path = match path {
            Some(_path) => _path.to_owned(),
            None => {
                let _config_path_or_err = Config::get_config_path();
                match _config_path_or_err {
                    Ok(some_path) => some_path,
                    Err(e) => return Err(e.into())
                }
            }
        };
        let out_str = match &self.toml {
            None => crate::config_template::get_config_template_string(&self),
            Some(toml) => {
                Ok(toml.to_string())
            }
        } ;
        match std::fs::write(config_path, out_str.unwrap()) {
            Ok(_) => Ok(()),
            Err(e) => Err(e.into()),
        }
    }

    pub fn get_config_path() -> anyhow::Result<PathBuf> {
        let basedirs = match BaseDirs::new() {
            Some(basedirs) => basedirs,
            None => {
                return Err(SystemError::BASE_DIRS_ERROR.into());
            }
        };
        trace!("Getting config path...");
        let config_path = basedirs.config_dir().join(Path::new("bak.conf"));
        trace!("Got config path: {}", config_path.to_string_lossy());
        let config_path_str = config_path.to_str().unwrap();
        if cfg!(unix) && config_path_str.contains("root") {
            trace!("Root detected. Checking for sudolike conditions...");
            let _actual_user = String::from_utf8(Command::new("logname").output()?.stdout)?;
            let actual_user = _actual_user.strip_suffix('\n').unwrap();
            if actual_user != "root" {
                trace!("sudo detected. Falling back on actual user");
                let pid = std::process::id();
                let _process_name_bytes = Command::new("ps").args(["-p", &pid.to_string(), "-o", "comm="]).output()?.stdout;
                let mut process_name = String::from_utf8(_process_name_bytes)?;
                process_name = process_name.strip_suffix('\n').unwrap().to_string();
                let run_command: String = process_name + " get-config";
                let mut actual_config_cmd = Command::new("runuser");
                actual_config_cmd.args(["-l",
                                        &actual_user,
                                        "-c",
                                        // &_test_ps_name,
                                        &run_command,
                                        ]);
                let _actual_config_path = actual_config_cmd.output()?.stdout;
                let mut actual_config_path = str::from_utf8(&_actual_config_path)?;
                actual_config_path = actual_config_path.strip_suffix("\n").unwrap();
                return Ok(PathBuf::from(actual_config_path));
                // return Err(anyhow::anyhow!(format!("{:#?}", actual_config_cmd)));
                // return Err(anyhow::anyhow!(String::from_utf8(actual_config_path)?));
                // return Err(anyhow::anyhow!(run_command))
            }
        }
        Ok(config_path)
    }
}
