[package]
name = "bak"
authors = ["ChanceNCounter <ChanceNCounter@icloud.com>"]
repository = "https://github.com/bakfile/bak"
version = "0.3.0" # tracks version of `bak` binary, not underlying `bakfile` library
edition = "2021"

[[bin]]
name = "bak"
path = "src/bin/bak/main.rs"

[dependencies]
bakfile = {path = "src/lib"}

anyhow = "1.0.94"
log = "0.4.22"
clap = { version = "4.5.4", features = ["cargo"] }
semver = { version = "1.0.23", features = ["serde"] }
env_logger = "0.11.5"
